sudo: required
language: generic
services:
  - docker
before_insall:
  - echo "start Creating an image with dockerfile"
  - docker build -t jiniworld/docker-react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true jiniworld/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Docker-react-app-env-2"
  bucket_name: "elasticbeanstalk-ap-northeast-2-825533217975"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY